version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/ti-import-to-ng-siem/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
